USE numbeo_col;

INSERT INTO cities (city_id, city_name, country, region)
VALUES
	(DEFAULT, 'Cairo', 'Egypt', 'Africa'),
    (DEFAULT, 'Cape Town', 'South Africa', 'Africa'),
    (DEFAULT, 'Lagos', 'Nigeria', 'Africa'),
    (DEFAULT, 'Nairobi', 'Kenya', 'Africa'),
    (DEFAULT, 'Johannesburg', 'South Africa', 'Africa'),
    (DEFAULT, 'Casablanca', 'Morocco', 'Africa'),
    (DEFAULT, 'Atlanta', 'United States', 'North America'),
    (DEFAULT, 'Buenos Aires', 'Argentina', 'South America'),
    (DEFAULT, 'Caracas', 'Venezuela', 'South America'),
    (DEFAULT, 'Chicago', 'United States', 'North America'),
    (DEFAULT, 'Dallas', 'United States', 'North America'),
    (DEFAULT, 'Guadalajara', 'Mexico', 'North America'),
    (DEFAULT, 'Honolulu', 'United States', 'North America'),
    (DEFAULT, 'Jacksonville', 'United States', 'North America'),
    (DEFAULT, 'Los Angeles', 'United States', 'North America'),
    (DEFAULT, 'Miami', 'United States', 'North America'),
    (DEFAULT, 'Medellin', 'Colombia', 'South America'),
    (DEFAULT, 'Montreal', 'Canada', 'North America'),
    (DEFAULT, 'New York', 'United States', 'North America'),
    (DEFAULT, 'Ottawa', 'Canada', 'North America'),
    (DEFAULT, 'Santiago', 'Chile', 'South America'),
    (DEFAULT, 'Rio de Janeiro', 'Brazil', 'South America'),
    (DEFAULT, 'Mexico City', 'Mexico', 'North America'),
    (DEFAULT, 'Tampa', 'United States', 'North America'),
    (DEFAULT, 'Toronto', 'Canada', 'North America'),
    (DEFAULT, 'Vancouver', 'Canada', 'North America'),
    (DEFAULT, 'Sao Paulo', 'Brazil', 'South America'),
    (DEFAULT, 'Bali', 'Indonesia', 'Southeast Asia'),
    (DEFAULT, 'Bangkok', 'Thailand', 'Southeast Asia'),
    (DEFAULT, 'Beijing', 'China', 'Far East'),
    (DEFAULT, 'Chiang Mai', 'Thailand', 'Southeast Asia'),
    (DEFAULT, 'Delhi', 'India', 'South Asia'),
    (DEFAULT, 'Dhaka', 'Bangladesh', 'South Asia'),
    (DEFAULT, 'Dubai', 'United Arab Emirates', 'Middle East'),
    (DEFAULT, 'Hanoi', 'Vietnam', 'Southeast Asia'),
    (DEFAULT, 'Ho Chi Minh City', 'Vietnam', 'Southeast Asia'),
    (DEFAULT, 'Istanbul', 'Turkey', 'Middle East'),
    (DEFAULT, 'Jakarta', 'Indonesia', 'Southeast Asia'),
    (DEFAULT, 'Jerusalem', 'Israel', 'Middle East'),
    (DEFAULT, 'Tel Aviv-Yafo', 'Israel', 'Middle East'),
    (DEFAULT, 'Abu Dhabi', 'United Arab Emirates', 'Middle East'),
    (DEFAULT, 'Riyadh', 'Saudi Arabia', 'Middle East'),
	(DEFAULT, 'Tehran', 'Iran', 'Middle East'),
    (DEFAULT, 'Islamabad', 'Pakistan', 'South Asia'),
    (DEFAULT, 'Kabul', 'Afghanistan', 'South Asia'),
    (DEFAULT, 'Kuala Lumpur', 'Malaysia', 'Southeast Asia'),
    (DEFAULT, 'Manila', 'Philippines', 'Southeast Asia'),
    (DEFAULT, 'Mumbai', 'India', 'South Asia'),
    (DEFAULT, 'Colombo', 'Sri Lanka', 'South Asia'),
    (DEFAULT, 'Phuket', 'Thailand', 'Southeast Asia'),
    (DEFAULT, 'Seoul', 'South Korea', 'Far East'),
    (DEFAULT, 'Shanghai', 'China', 'Far East'),
    (DEFAULT, 'Singapore', 'Singapore', 'Southeast Asia'),
    (DEFAULT, 'Taipei', 'Taiwan', 'Far East'),
    (DEFAULT, 'Tokyo', 'Japan', 'Far East'),
    (DEFAULT, 'Zurich', 'Switzerland', 'Western Europe'),
    (DEFAULT, 'Oslo', 'Norway', 'Northern Europe'),
    (DEFAULT, 'Reykjavik', 'Iceland', 'Northern Europe'),
    (DEFAULT, 'Copenhagen', 'Denmark', 'Northern Europe'),
    (DEFAULT, 'London', 'United Kingdom', 'Northern Europe'),
    (DEFAULT, 'Amsterdam', 'Netherlands', 'Western Europe'),
    (DEFAULT, 'Paris', 'France', 'Western Europe'),
    (DEFAULT, 'Stockholm', 'Sweden', 'Northern Europe'),
    (DEFAULT, 'Dublin', 'Ireland', 'Northern Europe'),
    (DEFAULT, 'Helsinki', 'Finland', 'Northern Europe'),
    (DEFAULT, 'Munich', 'Germany', 'Western Europe'),
    (DEFAULT, 'Milan', 'Italy', 'Southern Europe'),
    (DEFAULT, 'Bristol', 'United Kingdom', 'Northern Europe'),
    (DEFAULT, 'Brussels', 'Belgium', 'Western Europe'),
    (DEFAULT, 'Manchester', 'United Kingdom', 'Northern Europe'),
    (DEFAULT, 'Liverpool', 'United Kingdom', 'Northern Europe'),
    (DEFAULT, 'Berlin', 'Germany', 'Western Europe'),
    (DEFAULT, 'Florence', 'Italy', 'Southern Europe'),
    (DEFAULT, 'Rome', 'Italy', 'Southern Europe'),
    (DEFAULT, 'Vienna', 'Austria', 'Western Europe'),
    (DEFAULT, 'Naples', 'Italy', 'Southern Europe'),
    (DEFAULT, 'Madrid', 'Spain', 'Southern Europe'),
    (DEFAULT, 'Barcelona', 'Spain', 'Southern Europe'),
    (DEFAULT, 'Athens', 'Greece', 'Southern Europe'),
    (DEFAULT, 'Valencia', 'Spain', 'Southern Europe'),
    (DEFAULT, 'Prague', 'Czech Republic', 'Eastern Europe'),
    (DEFAULT, 'Lisbon', 'Portugal', 'Southern Europe'),
    (DEFAULT, 'Porto', 'Portugal', 'Southern Europe'),
    (DEFAULT, 'Sofia', 'Bulgaria', 'Eastern Europe'),
    (DEFAULT, 'Bucharest', 'Romania', 'Eastern Europe'),
    (DEFAULT, 'Warsaw', 'Poland', 'Eastern Europe'),
    (DEFAULT, 'Moscow', 'Russia', 'Eastern Europe'),
    (DEFAULT, 'Budapest', 'Hungary', 'Eastern Europe'),
    (DEFAULT, 'Belgrade', 'Serbia', 'Eastern Europe'),
    (DEFAULT, 'Saint Petersburg', 'Russia', 'Eastern Europe'),
    (DEFAULT, 'Sydney', 'Australia', 'Oceania'),
    (DEFAULT, 'Auckland', 'New Zealand', 'Oceania'),
    (DEFAULT, 'Melbourne', 'Australia', 'Oceania'),
    (DEFAULT, 'Suva', 'Fiji', 'Oceania'),
    (DEFAULT, 'Kathmandu', 'Nepal', 'South Asia'),
    (DEFAULT, 'Wellington', 'New Zealand', 'Oceania'),
    (DEFAULT, 'Hong Kong', 'China', 'Far East'),
    (DEFAULT, 'Osaka', 'Japan', 'Far East'),
    (DEFAULT, 'Quito', 'Ecuador', 'South America'),
    (DEFAULT, 'Lima', 'Peru', 'South America')
